spring.datasource.url=jdbc:mysql://localhost:3306/iot_fitness?useSSL=false&serverTimezone=America/Mexico_City
spring.datasource.username=root
spring.datasource.password=201940004

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialecto de MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
